### ISSUE TITLE
Encontro 09 - Importação de dados

### ISSUE THREAD

**Issue by beatrizmilz** [R-Ladies-Sao-Paulo/2024-clube-do-livro-r4ds#10]
## Definir pontos importantes

- Antes de criar o encontro, é bom já ter definido:
   - [x] Qual é o capítulo do livro a ser abordado no encontro? [Importação de dados](https://cienciadedatos.github.io/pt-r4ds/data-import.html)
   - [x] O capítulo está traduzido?
   - [x] Quem vai apresentar? @ceciliadcamargo
   - [x] Qual será o dia e horário que o encontro vai acontecer? (que funcione para quem vai apresentar) -> Setembro!

## Estruturar o encontro
 
Com essas informações, esses são os passos necessários:

- [x] Verificar se as informações acima já estão atualizadas aqui: https://github.com/R-Ladies-Sao-Paulo/2024-clube-do-livro-r4ds

- [x] Solicitar a bio e foto da pessoa que irá apresentar (é usado no Meetup)

- [x] No Canva (na conta da R-Ladies SP), já temos um template para a imagem de divulgação. É necessário duplicar a imagem e alterar as informações relevantes (número do encontro, tema, etc).

- [x] Criar o encontro no Streamyard (isso é necessário para a transmissão no Youtube). Recomendamos olhar o último evento do clube do livro, e seguir o padrão utilizado (nomenclatura, etc). @beatrizmilz

- [x] Criar o evento no Meetup. É necessário fazer uma cópia do último evento do clube do livro, e aí alterar as informações necessárias.

- [x] Adicionar na agenda do Google Agenda do grupo @beatrizmilz

- [x] Divulgação: Postar nas redes sociais para divulgar o encontro
   - [x] Mailing, alguns dias antes da atividade @beatrizmilz
   - [x] Mailing, no dia da atividade @beatrizmilz
   - [x] Instagram
   - [x] Linkedin
   - [x] Telegram

- [x] Checar se na [lista de presença](https://drive.google.com/drive/folders/10eZe552leUOv4jS1CNfHVoivjoUHiIN8?usp=sharing) apresenta a opção para o encontro

- [x] Preparar slide do início do evento (modelo no canva)

# Pós-encontro

- [ ] Atualizar o [arquivo compartilhado](https://docs.google.com/document/d/1xCn5gxK47tj9lRpDovwGNlza9i1FX2VBixo1V7VtUUs/edit?usp=sharing) com links, slides, etc

**Comment by beatrizmilz** [comment]
@ceciliadcamargo tem interesse em participar :tada:

Ainda não temos uma data definida!

Datas que eu tenho disponibilidade em setembro:
- 04/09 - quarta-feira
- 10/09 - terça
- 11/09 - quarta
- 12/09 - quinta
- 17/09 - terça
- 18/09 - quarta
- 19/09 - quinta

@ceciliadcamargo e @Luaaalex, quando possível, poderiam me dizer se tem disponibilidade em alguma dessas datas? Obrigada!

**Comment by ceciliadcamargo** [comment]
Boa tarde. Tenho disponibilidade nos dias 17, 18 ou 19!

**Comment by beatrizmilz** [comment]
> Boa tarde. Tenho disponibilidade nos dias 17, 18 ou 19!

Obrigada @ceciliadcamargo !
@Luaaalex imagino que por enquanto sua agenda está bem corrida.
Você acha que consegue participar em alguma dessas datas?
Obrigada <3

**Comment by beatrizmilz** [comment]
@ceciliadcamargo , a Lu se mudou agora e deve estar na adaptação.
Vamos deixar para quinta-feira então? dia 19/09.
Se você puder participar @Luaaalex vai ser ótimo, mas sem pressão!

**Comment by beatrizmilz** [comment]
@ceciliadcamargo poderia me passar uma foto e uma mini bio? precisamos dessa info no meetup!

**Comment by ceciliadcamargo** [comment]
@beatrizmilz de acordo com a data! Eu te mando as informações por aqui ou pelo telegram?

**Comment by beatrizmilz** [comment]
> @beatrizmilz de acordo com a data! Eu te mando as informações por aqui ou pelo telegram?

Pode ser por aqui mesmo! Obrigada!

**Comment by beatrizmilz** [comment]
> Oi gente, Consigo no dia 19/8 tambem. Eu vou preparar as artes pra divulgação.

Ebaaaa! Ótimo que você vai poder participar!

**Comment by beatrizmilz** [comment]
Youtube: https://www.youtube.com/watch?v=BvXy7rC-b2g

**Comment by beatrizmilz** [comment]
Meetup: https://www.meetup.com/rladies-sao-paulo/events/303179550/?utm_medium=referral&utm_campaign=share-btn_savedevents_share_modal&utm_source=link

**Comment by beatrizmilz** [comment]
@Luaaalex criei duas imagens de divulgação! Estão no Canva e salvei uma cópia aqui para facilitar: https://github.com/R-Ladies-Sao-Paulo/2024-clube-do-livro-r4ds/tree/main/encontro_9

**Comment by ceciliadcamargo** [comment]
> > @beatrizmilz de acordo com a data! Eu te mando as informações por aqui ou pelo telegram?
> 
> Pode ser por aqui mesmo! Obrigada!

Sou bióloga e atualmente curso bacharelado em Ciência de Dados. Possuo grande interesse em programação, análise de dados e código aberto. Participo da comunidade R-Ladies desde ano passado.

**Comment by beatrizmilz** [comment]
https://www.instagram.com/p/C_3niY_vOqi/
