### ISSUE TITLE
Submissão para a Latin-R - Clube do livro

### ISSUE THREAD

**Issue by beatrizmilz** [R-Ladies-Sao-Paulo/2024-clube-do-livro-r4ds#14]
Oi pessoal, tudo bem?
Estou preparando uma submissão para a Latin-R sobre o clube do livro: https://latinr.org/pt/blog/pt/2024-07-09-apresentacao-trabalhos-2024.html

Link:
https://docs.google.com/document/d/1DhBhWJ4-fdn2h3tiM4tE63XgRyE1prGK_thdIBQxGWs/edit?usp=sharing

A submissão é curta, só pode ter 2 páginas.

Por enquanto, estou listando a @Luaaalex e eu como co-autoras.

Mais alguém que tem participado do clube do livro (seja organizando, apresentando, assistindo) quer contribuir como co-autora?
@KarinaFerraraBarros @accustodio @fernandaperes @ceciliadcamargo ?

**Comment by KarinaFerraraBarros** [comment]
Bea! Dei uma sumida, estava com a vida meio atribulada. Obrigada pelo convite e espero que tenha dado certo. Em uma próxima oportunidade quero participar sim! Voltando aos poucos para as atividades, espero conseguir acompanhar o proximo encontro do Clube.

**Comment by KarinaFerraraBarros** [comment]
Está sim! Coisas boas... depois te conto. 
Que bom! O texto ficou ótimo, parabéns! Dessa vez fico na plateia kk
