### ISSUE TITLE
Encontro 03

### ISSUE THREAD

**Issue by beatrizmilz** [R-Ladies-Sao-Paulo/2024-clube-do-livro-r4ds#4]
## Definir pontos importantes

- Antes de criar o encontro, é bom já ter definido:
   - [x] Qual é o capítulo do livro a ser abordado no encontro?  - [Fluxo de Trabalho: básico](https://cienciadedatos.github.io/pt-r4ds/workflow-basics.html) / [Fluxo de Trabalho: Scripts e Projetos](https://cienciadedatos.github.io/pt-r4ds/workflow-scripts.html)
   - [x] O capítulo está traduzido? https://github.com/orgs/cienciadedatos/projects/2/views/1?pane=issue&itemId=37996249 / https://github.com/cienciadedatos/pt-r4ds/pull/86
   - [x] Quem vai apresentar? - Fernanda Peres @fernandaperes
   - [x] Qual será o dia e horário que o encontro vai acontecer? (que funcione para quem vai apresentar) - 22/03!

## Estruturar o encontro
 
Com essas informações, esses são os passos necessários:

- [x] Verificar se as informações acima já estão atualizadas aqui: https://github.com/R-Ladies-Sao-Paulo/2024-clube-do-livro-r4ds

- [x] No Canva (na conta da R-Ladies SP), já temos um template para a imagem de divulgação. É necessário duplicar a imagem e alterar as informações relevantes (número do encontro, tema, etc).

- [x] Criar o encontro no Streamyard (isso é necessário para a transmissão no Youtube). Recomendamos olhar o último evento do clube do livro, e seguir o padrão utilizado (nomenclatura, etc). @beatrizmilz

- [x] Criar o evento no Meetup. É necessário fazer uma cópia do último evento do clube do livro, e aí alterar as informações necessárias.

- [x] Adicionar na agenda do Google Agenda do grupo @beatrizmilz

- [x] Divulgação: Postar nas redes sociais para divulgar o encontro 
   - [x] Mailing @beatrizmilz
   - [x] Instagram
   - [x] Linkedin
   - [x] Telegram

- [x] Checar se na lista de presença apresenta a opção para o encontro

# Pós-encontro

- [x] Atualizar o arquivo compartilhado com links, slides, etc

**Comment by beatrizmilz** [comment]
@fernandaperes Fe, então dia 22/04 funciona para você?

**Comment by fernandaperes** [comment]
> @fernandaperes Fe, então dia 22/04 funciona para você?

Sim! Vamos deixar para dia 22/04 mesmo :)

**Comment by beatrizmilz** [comment]
> > @fernandaperes Fe, então dia 22/04 funciona para você?
> 
> Sim! Vamos deixar para dia 22/04 mesmo :)

Ótimo! Os capítulos estão traduzidos no site!
