### ISSUE TITLE
Encontro 04 - Fluxo de trabalho (Parte 2)

### ISSUE THREAD

**Issue by beatrizmilz** [R-Ladies-Sao-Paulo/2024-clube-do-livro-r4ds#7]
## Definir pontos importantes

- Antes de criar o encontro, é bom já ter definido:
   - [x] Qual é o capítulo do livro a ser abordado no encontro? [Fluxo de trabalho: estilo de código](https://cienciadedatos.github.io/pt-r4ds/workflow-style.html) / [Fluxo de trabalho: buscando ajuda](https://cienciadedatos.github.io/pt-r4ds/workflow-help.html)
   - [x] O capítulo está traduzido?
   - [x] Quem vai apresentar? @KarinaFerraraBarros
   - [x] Qual será o dia e horário que o encontro vai acontecer? (que funcione para quem vai apresentar)

## Estruturar o encontro
 
Com essas informações, esses são os passos necessários:

- [x] Verificar se as informações acima já estão atualizadas aqui: https://github.com/R-Ladies-Sao-Paulo/2024-clube-do-livro-r4ds

- [x] Obter a bio e foto da pessoa que irá apresentar (é usado no Meetup) @KarinaFerraraBarros 

- [x] No Canva (na conta da R-Ladies SP), já temos um template para a imagem de divulgação. É necessário duplicar a imagem e alterar as informações relevantes (número do encontro, tema, etc).

- [x] Criar o encontro no Streamyard (isso é necessário para a transmissão no Youtube). Recomendamos olhar o último evento do clube do livro, e seguir o padrão utilizado (nomenclatura, etc). @beatrizmilz

- [x] Criar o evento no Meetup. É necessário fazer uma cópia do último evento do clube do livro, e aí alterar as informações necessárias.

- [x] Adicionar na agenda do Google Agenda do grupo @beatrizmilz

- [x] Divulgação: Postar nas redes sociais para divulgar o encontro 
   - [x] Mailing @beatrizmilz
   - [x] Instagram
   - [x] Linkedin
   - [x] Telegram

- [x] Checar se na lista de presença apresenta a opção para o encontro

# Pós-encontro

- [x] Atualizar o arquivo compartilhado com links, slides, etc

**Comment by beatrizmilz** [comment]
Oi @KarinaFerraraBarros, tudo bem?
A data que está no arquivo README para você? terça 28/05, 19h.
Se não funcionar, poderia sugerir algumas opções entre terça e quintas-feiras, a partir do dia 21/05?
Obrigada! 🎉

**Comment by KarinaFerraraBarros** [comment]
@beatrizmilz combinado dia 28/05! Tudo certo com a data. 
Queria entender quais atividades da lista eu faço... algumas tem seu nome e outras não (meetup e canva).

**Comment by beatrizmilz** [comment]
> @beatrizmilz combinado dia 28/05! Tudo certo com a data. Queria entender quais atividades da lista eu faço... algumas tem seu nome e outras não (meetup e canva).

Oi Karina!! ótimo! uma coisa que preciso é uma mini-bio sua: um texto sobre você - o que você estudou/estuda, com o que trabalha, essas coisas. Não precisa ser longo! Também preciso de uma foto, mas peguei a do Linkedin. Serve?

**Comment by beatrizmilz** [comment]
Criei no Meetup, mas podemos alterar o que precisar (ex. a bio da @KarinaFerraraBarros não está preenchida)

https://www.meetup.com/rladies-sao-paulo/events/300899069/

**Comment by beatrizmilz** [comment]
Criado o evento no Youtube: https://www.youtube.com/watch?v=NZWQPFy_g4g

@KarinaFerraraBarros : A chamada é feita via Streamyard. Você já usou?
No dia, enviarei o link do Streamyard para você e para a @Luaaalex, cerca de meia hora antes do evento.

**Comment by KarinaFerraraBarros** [comment]
Oi, Bea, segue mini-bio:

Mestre pelo Programa de Pós-graduação em Ciências da Comunicação da Escola de Comunicações e Artes da Universidade de São Paulo (PPGCOM- ECA/USP) e graduada em Comunicação Social com habilitação em Relações Públicas pela Escola de Comunicações e Artes da Universidade de São Paulo (ECA-USP). Atua com Análise de Resultados de Pesquisas na Fundação Instituto de Pesquisas Econômicas - FIPE (2015-atual). Estudante do MBA em Business Intelligence & Analytics (ECA-USP).

**Comment by KarinaFerraraBarros** [comment]
Tudo bem sobre a foto. 

Nunca usei Streamyard.

**Comment by beatrizmilz** [comment]
Obrigada pela Bio!!

Sobre o streamyard, talvez seria melhor a gente marcar um outro momento antes, para te mostrar o Streamyard com calma! O que acha?

**Comment by KarinaFerraraBarros** [comment]
Acho bom, Bea! Você pode na quinta? Posso qualquer horário

**Comment by beatrizmilz** [comment]
Olá! Eu poderia as 15h ou 17h. Algum desses funcionaria?

**Comment by KarinaFerraraBarros** [comment]
Oi, Bea! Posso às 17h.

**Comment by beatrizmilz** [comment]
combinado!!

Em qui., 16 de mai. de 2024 às 12:07, Karina Ferrara Barros <
***@***.***> escreveu:

**Comment by Luaaalex** [comment]
Oie! Desculpem pela ausência esses dias!
@beatrizmilz segue o texto para divulgação nas mídias

📚✨ Convite especial! ✨📚

Venha participar do nosso próximo encontro do Clube do Livro "R For Data Science"! No dia 28/05 às 19h, teremos a presença inspiradora da Karina Ferrara Barros.

Karina é Mestre pelo Programa de Pós-graduação em Ciências da Comunicação da Escola de Comunicações e Artes da Universidade de São Paulo (PPGCOM- ECA/USP) e graduada em Comunicação Social com habilitação em Relações Públicas pela Escola de Comunicações e Artes da Universidade de São Paulo (ECA-USP)..

Já garantiu sua vaga? Não perca! Inscreva-se agora! 👇
https://www.meetup.com/rladies-sao-paulo/events/300899069/

#clubedolivro #rfordatascience #eventoonline #rladiessp

**Comment by beatrizmilz** [comment]
> Oie! Desculpem pela ausência esses dias! @beatrizmilz segue o texto para divulgação nas mídias...
> 
> 📚✨ Convite especial! ✨📚
> 
> Venha participar do nosso próximo encontro do Clube do Livro "R For Data Science"! No dia 28/05 às 19h, teremos a presença da Karina Ferrara Barros, apresentando o tema "fluxos de trabalho - parte 2"!
> 
> Karina é Mestre pelo Programa de Pós-graduação em Ciências da Comunicação da Escola de Comunicações e Artes da Universidade de São Paulo (PPGCOM- ECA/USP) e graduada em Comunicação Social com habilitação em Relações Públicas pela Escola de Comunicações e Artes da Universidade de São Paulo (ECA-USP)..
> 
> Já garantiu sua vaga? Não perca! Inscreva-se agora! 👇 https://www.meetup.com/rladies-sao-paulo/events/300899069/
> 
> #clubedolivro #rfordatascience #eventoonline #rladiessp

Muito obrigada Lu!
