### ISSUE TITLE
Encontro 08 - Organização de dados

### ISSUE THREAD

**Issue by beatrizmilz** [R-Ladies-Sao-Paulo/2024-clube-do-livro-r4ds#9]
## Definir pontos importantes

- Antes de criar o encontro, é bom já ter definido:
   - [x] Qual é o capítulo do livro a ser abordado no encontro? [Organização de dados](https://cienciadedatos.github.io/pt-r4ds/data-tidy.html)
   - [x] O capítulo está traduzido?
   - [x] Quem vai apresentar? @accustodio 
   - [x] Qual será o dia e horário que o encontro vai acontecer? (que funcione para quem vai apresentar) 06/08

## Estruturar o encontro
 
Com essas informações, esses são os passos necessários:

- [x] Verificar se as informações acima já estão atualizadas aqui: https://github.com/R-Ladies-Sao-Paulo/2024-clube-do-livro-r4ds

- [x] Solicitar a bio e foto da pessoa que irá apresentar (é usado no Meetup)

- [x] No Canva (na conta da R-Ladies SP), já temos um template para a imagem de divulgação. É necessário duplicar a imagem e alterar as informações relevantes (número do encontro, tema, etc).

- [x] Criar o encontro no Streamyard (isso é necessário para a transmissão no Youtube). Recomendamos olhar o último evento do clube do livro, e seguir o padrão utilizado (nomenclatura, etc). @beatrizmilz

- [x] Criar o evento no Meetup. É necessário fazer uma cópia do último evento do clube do livro, e aí alterar as informações necessárias.

- [x] Adicionar na agenda do Google Agenda do grupo @beatrizmilz

- [x] Divulgação: Postar nas redes sociais para divulgar o encontro 
   - [x] Mailing, alguns dias antes da atividade @beatrizmilz
   - [x] Mailing, no dia da atividade @beatrizmilz 
   - [x] Instagram
   - [x] Linkedin
   - [x] Telegram

- [x] Checar se na lista de presença apresenta a opção para o encontro

- [x] Preparar slide do início do evento 

# Pós-encontro

- [x] Atualizar o [arquivo compartilhado](https://docs.google.com/document/d/1xCn5gxK47tj9lRpDovwGNlza9i1FX2VBixo1V7VtUUs/edit?usp=sharing) com links, slides, etc

**Comment by beatrizmilz** [comment]
@accustodio @Luaaalex vamos pensar na data desse encontro, considerando que será em agosto?

Por enquanto, as noites (19h) que eu posso durante a semana:
05/08 (segunda)
06/08 (terça)
07/08 (quarta)
12/08 (segunda)
13/08 (terça)
14/08 (quarta)
27/08 (terça)
28/08 (quinta)
Quais dessas datas vocês podem?

Outra coisa: para esse capítulo, você acha que precisa de 1 ou 2 encontros? @accustodio

**Comment by Luaaalex** [comment]
Oie! Tudo bem?
Gente, eu tenho uma viagem no dia 08/08, até esse dia vai ser um pouco caótico, pois é uma viagem de mudança.
Qualquer data após do dia 15 para frente eu já vou estar mais estabelecida.

**Comment by beatrizmilz** [comment]
Oi Lu! Obrigada!! @Luaaalex 
Dentre essas datas, você consegue @accustodio ?
27/08 (terça)
28/08 (quinta)

**Comment by accustodio** [comment]
Oiie, gente!
Infelizmente nessa última semana eu não consigo @Luaaalex  :/
Podemos fechar dia 06/08 (terça) ou 07/08 (quarta)? Prefiro dia 6, se for possível.

**Comment by accustodio** [comment]
@beatrizmilz sobre a quantidade de encontros para esse capítulo, a principio acho que dá pra fazer em um encontro sim.
Mas se eu perceber que fica melhor quebrar, atualizo vcs!

**Comment by beatrizmilz** [comment]
> Oiie, gente! Infelizmente nessa última semana de agosto eu não consigo @Luaaalex :/ Podemos fechar dia 06/08 (terça) ou 07/08 (quarta)? Prefiro dia 6, se for possível.

Tudo bem se fizermos esse encontro sem a sua confirmação @Luaaalex ? Se você conseguir, ótimo! Se não der, eu toco o encontro com a Angélica.

**Comment by Luaaalex** [comment]
Sem problemas,  podem seguir com essa data.  Eu aviso mais para frente se vou conseguir participar :)

**Comment by beatrizmilz** [comment]
Beleza! Então será dia 06/08, correto @accustodio ? Você pode passar uma minibio, e o link da foto que deseja usar para a divulgação no meetup? Obrigada!

**Comment by accustodio** [comment]
Isso mesmo, dia 06/08, combinado! Mais tarde mando a minibio lá no grupo

**Comment by beatrizmilz** [comment]
> Isso mesmo, dia 06/08, combinado! Mais tarde mando a minibio lá no grupo

Oi! Eba!! Obrigada!
Me avisa quando compartilhar os dados, por favor?
Pode ser aqui também!

<3

**Comment by beatrizmilz** [comment]
up!

**Comment by beatrizmilz** [comment]
@accustodio confirmou a data! Vou criar os conteúdos.

**Comment by beatrizmilz** [comment]
Não sei pq, mas não estou conseguindo acessar o site do meetup:
![imagem](https://github.com/user-attachments/assets/f61bd5b0-2e42-456a-bbb2-29284501689a)
E não é de hoje T_T

**Comment by accustodio** [comment]
Eita, @beatrizmilz o erro para acessar o meetup continua?

Segue a minibio, a foto te enviei no privado:

> Angélica é estatista e mestre em Ciência da Computação, com pesquisas nas áreas de Interpretabilidade de modelos opacos, Modelagem Uplift e Modelagem Hierárquica.
> Participa das comunidades R-Ladies e Pyladies São Paulo, cujo propósito é disseminar conhecimento e engajar mais mulheres na área da tecnologia.
> Atua como Cientista de Dados desde 2016 e é Professora no Programa de Data Science do Insper.

**Comment by beatrizmilz** [comment]
Mini bio da Angélica:
> Angélica é estatista e mestre em Ciência da Computação, com pesquisas nas áreas de Interpretabilidade de modelos opacos, Modelagem Uplift e Modelagem Hierárquica.
Participa das comunidades R-Ladies e Pyladies São Paulo, cujo propósito é disseminar conhecimento e engajar mais mulheres na área da tecnologia.
Atua como Cientista de Dados desde 2016 e é Professora no Programa de Data Science do Insper.

**Comment by beatrizmilz** [comment]
Gente, o problema com o meetup aparentemente é só no meu computador. A @hsvab disse que para ela funciona normalmente.
E no meu caso, funcionou no meu ipad! Criei por lá: https://www.meetup.com/pt-BR/rladies-sao-paulo/events/302611944/
